package vu.lt.mybatis.model;

public class Subjects {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SUBJECTS.STUDENT_ID
     *
     * @mbg.generated Tue May 17 04:20:44 EEST 2022
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SUBJECTS.SUBJECT_ID
     *
     * @mbg.generated Tue May 17 04:20:44 EEST 2022
     */
    private Integer subjectId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SUBJECTS.STUDENT_ID
     *
     * @return the value of PUBLIC.SUBJECTS.STUDENT_ID
     *
     * @mbg.generated Tue May 17 04:20:44 EEST 2022
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SUBJECTS.STUDENT_ID
     *
     * @param studentId the value for PUBLIC.SUBJECTS.STUDENT_ID
     *
     * @mbg.generated Tue May 17 04:20:44 EEST 2022
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SUBJECTS.SUBJECT_ID
     *
     * @return the value of PUBLIC.SUBJECTS.SUBJECT_ID
     *
     * @mbg.generated Tue May 17 04:20:44 EEST 2022
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SUBJECTS.SUBJECT_ID
     *
     * @param subjectId the value for PUBLIC.SUBJECTS.SUBJECT_ID
     *
     * @mbg.generated Tue May 17 04:20:44 EEST 2022
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }
}