package vu.lt.mybatis.model;

public class Subject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SUBJECT.ID
     *
     * @mbg.generated Tue Apr 19 23:57:44 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SUBJECT.NAME
     *
     * @mbg.generated Tue Apr 19 23:57:44 EEST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SUBJECT.UNIVERSITY
     *
     * @mbg.generated Tue Apr 19 23:57:44 EEST 2022
     */
    private String university;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SUBJECT.ID
     *
     * @return the value of PUBLIC.SUBJECT.ID
     *
     * @mbg.generated Tue Apr 19 23:57:44 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SUBJECT.ID
     *
     * @param id the value for PUBLIC.SUBJECT.ID
     *
     * @mbg.generated Tue Apr 19 23:57:44 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SUBJECT.NAME
     *
     * @return the value of PUBLIC.SUBJECT.NAME
     *
     * @mbg.generated Tue Apr 19 23:57:44 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SUBJECT.NAME
     *
     * @param name the value for PUBLIC.SUBJECT.NAME
     *
     * @mbg.generated Tue Apr 19 23:57:44 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SUBJECT.UNIVERSITY
     *
     * @return the value of PUBLIC.SUBJECT.UNIVERSITY
     *
     * @mbg.generated Tue Apr 19 23:57:44 EEST 2022
     */
    public String getUniversity() {
        return university;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SUBJECT.UNIVERSITY
     *
     * @param university the value for PUBLIC.SUBJECT.UNIVERSITY
     *
     * @mbg.generated Tue Apr 19 23:57:44 EEST 2022
     */
    public void setUniversity(String university) {
        this.university = university;
    }
}