package vu.lt.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import vu.lt.mybatis.model.Subjects;

@Mapper
public interface SubjectsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUBJECTS
     *
     * @mbg.generated Tue May 17 04:20:44 EEST 2022
     */
    int insert(Subjects record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUBJECTS
     *
     * @mbg.generated Tue May 17 04:20:44 EEST 2022
     */
    List<Subjects> selectAll();
}